apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: ado-scaledjob
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: ado-agent-job
          image: wolfgangofner/adoagentkeda # replace with your value
          imagePullPolicy: Always
          env:
          - name: AZP_URL
            value: https://dev.azure.com/programmingwithwolfgang # replace with your value
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: ado-agent-secret
                key: AZP_TOKEN
          - name: AZP_POOL
            value: Keda # replace with your value
          securityContext:
            privileged: true
  pollingInterval: 10
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10   
  scalingStrategy:
    strategy: "default"
  triggers:
  - type: azure-pipelines
    metadata:
      poolID:  "10" # <azure-devops-pool-id> (must be a string) (https://dev.azure.com/{Organization}/_apis/distributedtask/pools?api-version=7.0)
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZP_TOKEN"