trigger: none

resources:
- repo: self

pool: Keda

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: 'build'
    #     Dockerfile: '**/Dockerfile'
    #     buildContext: '.'
    #     tags: '$(tag)'

    - task: Bash@3
      displayName: Build Docker Image for DemoWeb
      inputs:
        targetType: inline
        script: |
          podman build -f $(Build.SourcesDirectory)/K8sAdoAgent/Dockerfile -t adodemoapp:$(tag) .